swarm:
  agents:
    - type: web_scraper
      n: 3  # More scrapers for broader data collection
    - type: data_analyst
      n: 2
    - type: legal_analyst
      n: 1  # Requires specialized skills, thus fewer in number
    - type: report_generator
      n: 1
    - type: notifier
      n: 1
  timeout_min: 15  # Longer timeout due to complexity of tasks
  run_dir: ./tmp/swarm
task:
  role: coordinator
  actions:
    - coordinate_data_collection
    - analyze_legal_implications
global_goal: Investigate financial flows and legal implications in the Panama and Paradise Papers.
goals:
  web_scraper:
    - scrape_new_publications
    - update_data_sources
  data_analyst:
    - perform_entity_recognition
    - conduct_network_analysis
  legal_analyst:
    - review_financial_practices
    - assess_legal_implications
  report_generator:
    - compile_detailed_reports
  notifier:
    - alert_stakeholders_of_key_findings
